# K Nearest Neighbor Classfication

In [ ]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target

In [3]:
# Split train-test datasets
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_train_X = iris_X[indices[:-10]]
iris_train_y = iris_y[indices[:-10]]

iris_test_X = iris_X[indices[-10:]]
iris_test_y = iris_y[indices[-10:]]

In [4]:
from sklearn.neighbors import KNeighborsClassifier 

In [5]:
knn_cls = KNeighborsClassifier()
knn_cls.fit(iris_train_X, iris_train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [6]:
knn_cls.predict(iris_test_X)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

In [7]:
iris_test_y # One error

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

# Linear Regression

In [8]:
# Prepare datasets
diabetes = datasets.load_diabetes()
dia_X_train = diabetes.data[:-20]
dia_y_train = diabetes.target[:-20]
dia_X_test = diabetes.data[-20:]
dia_y_test = diabetes.target[-20:]

In [9]:
from sklearn import linear_model 

In [13]:
LR_cls = linear_model.LinearRegression()
LR_cls.fit(dia_X_train, dia_y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [14]:
np.mean((LR_cls.predict(dia_X_test) - dia_y_test)**2)

2004.5676026898218

In [15]:
LR_cls.score(dia_X_test, dia_y_test)

0.5850753022690572

In [16]:
# Shrinkage TODO

In [21]:
alphas = np.logspace(-4, -1, 6)

### Sparsity Method

In [22]:
regr = linear_model.Lasso()
scores = [regr.set_params(alpha=alpha).fit(dia_X_train, dia_y_train).score(dia_X_test, dia_y_test) for alpha in alphas]

In [24]:
best_alpha = alphas[scores.index(np.max(scores))]

In [26]:
regr.alpha = best_alpha

In [27]:
regr.fit(dia_X_train, dia_y_train)

Lasso(alpha=0.025118864315095794, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=False, positive=False, precompute=False,
   random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [28]:
print(regr.coef_)

[   0.         -212.43764548  517.19478111  313.77959962 -160.8303982
   -0.         -187.19554705   69.38229038  508.66011217   71.84239008]


# Classfication

In [29]:
log = linear_model.LogisticRegression(solver='lbfgs', C=1e5, multi_class='multinomial')

In [31]:
log.fit(iris_train_X, iris_train_y)

LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='multinomial', n_jobs=None, penalty='l2',
          random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
          warm_start=False)

In [32]:
log.predict(iris_test_X)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

In [33]:
iris_test_y

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

# Support Vector Machines

In [37]:
from sklearn import svm
svc = svm.SVC(kernel='linear')
svc.fit(iris_train_X, iris_train_y)
svc.predict(iris_test_X)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

In [38]:
svc2 = svm.SVC(kernel='rbf')
svc2.fit(iris_train_X, iris_train_y)
svc2.predict(iris_test_X)

/usr/lib/python3/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])